INSERT INTO PRODUCT(ID, TITLE, DESCRIPTION, PRICE) VALUES (1, 'Lenovo Laptop', 'Description', 70.20);
INSERT INTO PRODUCT(ID, TITLE, DESCRIPTION, PRICE) VALUES (2, 'Headphones', 'Description', 10.30);
INSERT INTO PRODUCT(ID, TITLE, DESCRIPTION, PRICE) VALUES (3, 'Redmi Tv', 'Description', 40.10);
INSERT INTO PRODUCT(ID, TITLE, DESCRIPTION, PRICE) VALUES (4, 'Apple iPod', 'Description', 13.40);
INSERT INTO PRODUCT(ID, TITLE, DESCRIPTION, PRICE) VALUES (5, 'Dell Laptop', 'Description', 66.50);